# Setup
title:               Erik's Security Blog
tagline:             'Practicing Constant Vigilence'
description:         'This blog is a compilation of security ideas from Erik Elbieh. For questions or comments about this blog, please <a href="https://erikelbieh.com/contact">contact Erik</a>.'
url:                 https://engn33r.github.io/LiveSecurityBlog
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown
remote_theme:        poole/lanyon

# About/contact
author:
  name:              Erik Elbieh
  url:               https://erikelbieh.com
  email:             erik.elbieh@protonmail.com

# Gems
plugins:
  - jekyll-paginate
